"""'65550618f1d9' - remove post body."""

import sqlalchemy as sa

from alembic import op

#from lib.util_datetime import tzware_datetime
#from lib.util_sqlalchemy import AwareDateTime
"""
remove post body

Revision ID: 65550618f1d9
Revises: c6237177b156
Create Date: 2016-12-10 19:50:08.689544
"""

# Revision identifiers, used by Alembic.
revision = '65550618f1d9'
down_revision = 'c6237177b156'
branch_labels = None
depends_on = None


def upgrade():
    """Command to migrate database forward."""

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body')
    ### end Alembic commands ###


def downgrade():
    """Command to migrate database backwards."""

    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'posts',
        sa.Column(
            'body', sa.TEXT(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
