"""'c5d603bcc674' - fixing relationships."""

import sqlalchemy as sa

from alembic import op

#from lib.util_datetime import tzware_datetime
#from lib.util_sqlalchemy import AwareDateTime
"""
fixing relationships

Revision ID: c5d603bcc674
Revises: d01af963e6f2
Create Date: 2016-12-10 19:48:20.840059
"""

# Revision identifiers, used by Alembic.
revision = 'c5d603bcc674'
down_revision = 'd01af963e6f2'
branch_labels = None
depends_on = None


def upgrade():
    """Command to migrate database forward."""

    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    """Command to migrate database backwards."""

    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
