"""'d01af963e6f2' - adding post revisions."""

import sqlalchemy as sa

from alembic import op

from lib.util_datetime import tzware_datetime
from lib.util_sqlalchemy import AwareDateTime
"""
adding post revisions

Revision ID: d01af963e6f2
Revises: 6affe75c0cec
Create Date: 2016-12-10 18:20:18.514803
"""

# Revision identifiers, used by Alembic.
revision = 'd01af963e6f2'
down_revision = '6affe75c0cec'
branch_labels = None
depends_on = None


def upgrade():
    """Command to migrate database forward."""

    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'post_revision',
        sa.Column(
            'created_on', AwareDateTime(), nullable=True),
        sa.Column(
            'updated_on', AwareDateTime(), nullable=True),
        sa.Column(
            'id', sa.Integer(), nullable=False),
        sa.Column(
            'post_id', sa.Integer(), nullable=True),
        sa.Column(
            'diff', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ['post_id'],
            ['posts.id'], ),
        sa.PrimaryKeyConstraint('id'))
    op.create_table(
        'post_revisions',
        sa.Column(
            'revision_id', sa.Integer(), nullable=True),
        sa.Column(
            'post_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['post_id'],
            ['posts.id'], ),
        sa.ForeignKeyConstraint(
            ['revision_id'],
            ['post_revision.id'], ))
    ### end Alembic commands ###


def downgrade():
    """Command to migrate database backwards."""

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_revisions')
    op.drop_table('post_revision')
    ### end Alembic commands ###
