"""'9478ff6ae514' - make category a resource."""

import sqlalchemy as sa

from alembic import op

#from lib.util_datetime import tzware_datetime
from lib.util_sqlalchemy import AwareDateTime


"""
make category a resource

Revision ID: 9478ff6ae514
Revises: 65550618f1d9
Create Date: 2016-12-29 13:30:30.281068
"""

# Revision identifiers, used by Alembic.
revision = '9478ff6ae514'
down_revision = '65550618f1d9'
branch_labels = None
depends_on = None


def upgrade():
    """Command to migrate database forward."""

    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created_on', AwareDateTime(), nullable=True))
    op.add_column('categories', sa.Column('updated_on', AwareDateTime(), nullable=True))
    op.drop_column('posts', 'file_hash')
    ### end Alembic commands ###


def downgrade():
    """Command to migrate database backwards."""

    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('file_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('categories', 'updated_on')
    op.drop_column('categories', 'created_on')
    ### end Alembic commands ###
