"""'c6237177b156' - remove m2m table for revisions."""

import sqlalchemy as sa

from alembic import op

#from lib.util_datetime import tzware_datetime
#from lib.util_sqlalchemy import AwareDateTime
"""
remove m2m table for revisions

Revision ID: c6237177b156
Revises: c5d603bcc674
Create Date: 2016-12-10 19:49:22.617677
"""

# Revision identifiers, used by Alembic.
revision = 'c6237177b156'
down_revision = 'c5d603bcc674'
branch_labels = None
depends_on = None


def upgrade():
    """Command to migrate database forward."""

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_revisions')
    ### end Alembic commands ###


def downgrade():
    """Command to migrate database backwards."""

    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'post_revisions',
        sa.Column(
            'revision_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            'post_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ['post_id'], ['posts.id'], name='post_revisions_post_id_fkey'),
        sa.ForeignKeyConstraint(
            ['revision_id'], ['post_revision.id'],
            name='post_revisions_revision_id_fkey'))
    ### end Alembic commands ###
